### ISSUE TITLE
Velocidade do escaneamento 

### ISSUE THREAD

**Issue by kori-lab** [IagoManoel/pyort_scanmap#1]
O `for` em si é devagar por esperar cada função ser executada em sequencia, recomendo fortemente você dar uma olhada sobre `threads` no python, podendo assim executar **scans** de diversas portas paralelamente.

Links para estudo:

> https://pt.stackoverflow.com/questions/143552/entendendo-o-conceito-de-threads-na-prática-em-python
> https://realpython.com/intro-to-python-threading/

**Comment by IagoManoel** [comment]
Vlw mano, vou dar uma estudada sobre isso, não sabia que dava pra executar as coisas em paralelo
